### ISSUE TITLE
Implement Story Evaluator

### ISSUE THREAD

**Issue by datacrystals** [datacrystals/AIStoryWriter#34]
Currently, there is not a way for us to tell if our output is getting better - thus it would be good to build a tool where we can evaluate this automatically.

**Comment by LoggeL** [comment]
Features which could be interesting:
Character Building
World Building
Dialog Quality
Consistency
Writing Style
...

It's important to denote the judgement model in the scores since every model judges differently. 
Each point should be evaluated after a reason has been stated. Which would improve the reasoning of the llm. Also it might improve the robustness if we'd hand out examples of negatives in the prompt.
